### ISSUE TITLE
Add build status badge

### ISSUE THREAD

**Issue by ocxo** [boxen/puppet-nsq#1]

**Comment by mattheath** [comment]
I can add a badge, but can't set up the Travis hook for the Boxen org repos. @wfarr is someone able to set them up?

**Comment by ocxo** [comment]
It should be ready to go https://travis-ci.org/boxen/puppet-nsq

**Comment by mattheath** [comment]
@fromonesrc my bad, cheers!

**Comment by mattheath** [comment]
Fixed
